#!/bin/sh
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 NomDeTom
# Irate-Box: the hook every private repository uses (core.hooksPath, set by gitrepos.py). It
# queues a build for each pushed branch whose commit has a .irate-ci.sh; ci.py says how.
exec "$(dirname "$0")/../../irate-box" ci enqueue
