#!/usr/bin/env python3
"""Cumulative uptime clock — a wall-clock-independent time source.

Wall clock time is meaningless on this hardware. The Pi Zero W and Lyra Zero W have no
RTC, and the hub is offline by design so there is no NTP either: every boot starts at
the epoch, or at whatever was last written to disk. Anything that expires content
against the wall clock will either drop everything on first boot or nothing, ever.

This module counts *powered-on seconds accumulated across all boots* instead. It is
immune to clock jumps because it never reads the wall clock at all.

CLOCK_MONOTONIC and /proc/uptime are immune too, but both reset to zero on reboot --
and a field box gets power-cycled constantly, which would reset every TTL along with
them. So the total is persisted and re-based at startup, using
/proc/sys/kernel/random/boot_id (regenerated by the kernel on every boot) to tell a
reboot apart from a mere service restart.

Nothing here knows about messages, posts or HTTP. It is only a counter: consumers
record ticks() alongside their data and expire it by comparing against a later reading.

    clock = HubClock()
    clock.start()                          # background flush thread
    post["created"] = clock.ticks()
    ...
    if clock.ticks() - post["created"] > TTL:
        drop(post)

Run directly to inspect the counter:  python3 hubclock.py
"""

import json
import os
import threading
import time
from pathlib import Path

UPTIME_FILE = Path("/proc/uptime")
BOOT_ID_FILE = Path("/proc/sys/kernel/random/boot_id")

DEFAULT_STATE = Path(os.environ.get("HUB_CLOCK_STATE", "/var/lib/hub/clock.json"))

# How often the total is written to disk. This is the whole durability trade: seconds
# accrued since the last flush are lost to a power cut, and every flush is an SD card
# write. A minute loses at most a minute of counted uptime and costs ~1440 small
# writes a day, which any wear-levelling card shrugs off.
DEFAULT_FLUSH_INTERVAL = 60.0


def _uptime():
    """Seconds since boot. Includes time spent suspended, unlike CLOCK_MONOTONIC."""
    try:
        return float(UPTIME_FILE.read_text().split()[0])
    except (OSError, ValueError):
        # Not Linux, or /proc unavailable. time.monotonic() has the same reset-on-boot
        # behaviour, which the persistence layer above already handles.
        return time.monotonic()


def _boot_id():
    try:
        return BOOT_ID_FILE.read_text().strip()
    except OSError:
        return ""


class HubClock:
    def __init__(self, state_path=DEFAULT_STATE, flush_interval=DEFAULT_FLUSH_INTERVAL):
        self.state_path = Path(state_path)
        self.flush_interval = flush_interval
        self._lock = threading.Lock()
        self._stop = threading.Event()
        self._thread = None
        self._boot_id = _boot_id()
        self._offset = 0.0
        self._load()

    def _load(self):
        state = {}
        try:
            state = json.loads(self.state_path.read_text())
        except (OSError, ValueError):
            pass  # First run, or a torn write from a power cut. Start from zero.

        offset = float(state.get("offset", 0.0))
        stored_boot = state.get("boot_id", "")
        stored_uptime = float(state.get("uptime", 0.0))

        if stored_boot and stored_boot == self._boot_id:
            # Same boot -- a service restart, not a reboot. Resume where we left off.
            self._offset = offset
        else:
            # New boot. Credit everything the previous boot had accrued as of its last
            # flush; the gap between that flush and the power cut is unrecoverable.
            self._offset = offset + stored_uptime

    def ticks(self):
        """Cumulative seconds this hub has been powered on, across all boots."""
        return self._offset + _uptime()

    def flush(self):
        payload = {
            "offset": self._offset,
            "boot_id": self._boot_id,
            "uptime": _uptime(),
        }
        tmp = self.state_path.parent / (self.state_path.name + ".tmp")
        with self._lock:
            self.state_path.parent.mkdir(parents=True, exist_ok=True)
            # Write-and-rename: power can vanish mid-write, and a truncated state file
            # would silently reset the counter to zero.
            with open(tmp, "w") as fh:
                json.dump(payload, fh)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp, self.state_path)
            dir_fd = os.open(self.state_path.parent, os.O_RDONLY)
            try:
                os.fsync(dir_fd)  # make the rename itself durable
            finally:
                os.close(dir_fd)

    def _run(self):
        while not self._stop.wait(self.flush_interval):
            try:
                self.flush()
            except OSError:
                pass  # read-only fs or full card; keep counting in memory regardless

    def start(self):
        """Begin flushing in the background. Safe to call once."""
        if self._thread is not None:
            return
        self.flush()
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def stop(self):
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=2)
            self._thread = None
        try:
            self.flush()
        except OSError:
            pass


def format_age(seconds):
    """Render a tick delta as an age.

    Ticks are a duration, never a date -- there is no wall clock to anchor them to, so
    they must always be shown relative to now.
    """
    seconds = max(0, int(seconds))
    if seconds < 60:
        return "just now"
    minutes = seconds // 60
    if minutes < 60:
        return f"{minutes}m"
    hours, minutes = divmod(minutes, 60)
    if hours < 24:
        return f"{hours}h {minutes}m" if minutes else f"{hours}h"
    days, hours = divmod(hours, 24)
    return f"{days}d {hours}h" if hours else f"{days}d"


_shared = None


def get_clock():
    """Process-wide clock, so every consumer expires against the same counter."""
    global _shared
    if _shared is None:
        _shared = HubClock()
    return _shared


if __name__ == "__main__":
    clock = HubClock()
    total = clock.ticks()
    print(f"state file:    {clock.state_path}")
    print(f"boot id:       {clock._boot_id or '(unavailable)'}")
    print(f"this boot:     {format_age(_uptime())}")
    print(f"cumulative:    {format_age(total)}  ({total:.0f}s)")
