# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 NomDeTom
# Licences for files that cannot carry a header (REUSE, https://reuse.software).
version = 1

[[annotations]]
path = "apps.d/*.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 NomDeTom"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "tests/jsdom/*.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 NomDeTom"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "web/art/*.webp"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 NomDeTom"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["packaging/deb/control", "packaging/deb/copyright"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 NomDeTom"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "irate.code-workspace"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 NomDeTom"
SPDX-License-Identifier = "MIT"
