# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 NomDeTom
"""Who may open each app: public, private or off (/admin, Apps and Add-ons).

  public    on the home page for everyone; the route is open (or, for the shell and the
            Syncthing page, still behind the admin login: "login_always")
  private   not on the home page; the route asks for the admin login
  off       not on the home page; the route answers 404, and an add-on's service is stopped

The choice is root's (/etc/hub/access.json, written by the root helper), because it changes
the web server's config: for nginx, a file of `set` lines the site includes at server level
($irate_box_auth_<id>, $irate_box_off_<id>); for Caddy, one snippet per app imported where its
route is. The root helper leaves a copy in the hub's control folder, which the hub reads to
leave tiles and list entries out.

The apps that can be switched are the ones the web-server configs gate (ROUTED). Their
manifests' "access" part gives the default and the wording; an app without a manifest keeps
its default. Stdlib only.
"""

import json
import re

MODES = ("public", "private", "off")
# id -> (default, login always): what config/irate-box.nginx and config/Caddyfile gate.
ROUTED = {
    "draw": ("public", False), "mermaid": ("public", False), "serial": ("public", False),
    "tools": ("public", False), "flasher": ("public", False), "wiki": ("public", False),
    "git": ("public", False), "drop": ("public", False), "notes": ("public", False),
    "mqtt": ("public", False), "term": ("public", True), "sync": ("private", True),
}
REALM = "Irate-Box"


def defaults():
    return {i: d for i, (d, _) in ROUTED.items()}


def clean(data):
    """Only known ids and modes; anything else falls back to the default."""
    out = defaults()
    if isinstance(data, dict):
        for i, mode in data.items():
            if i in ROUTED and mode in MODES:
                out[i] = mode
    return out


def read(path):
    try:
        return clean(json.loads(path.read_text()))
    except (OSError, ValueError):
        return defaults()


def apps(manifests):
    """The switchable apps for /admin, in manifest order: [{id, title, default, login, note,
    kind (app, addon or builtin: where /admin shows it), unit (off stops a service)}]."""
    out = []
    for m in manifests:
        if m["id"] not in ROUTED:
            continue
        a = m.get("access", {})
        title = (m.get("tile") or {}).get("name") or (m.get("addon") or {}).get("title") \
            or (m.get("status") or {}).get("name") or m["id"]
        kind = "app" if m.get("install") else "addon" if m.get("addon") else "builtin"
        out.append({"id": m["id"], "title": a.get("title", title), "default": ROUTED[m["id"]][0],
                    "login": ROUTED[m["id"]][1], "note": a.get("note", ""), "kind": kind,
                    "unit": bool((m.get("status") or {}).get("control"))})
    return out


def var(i):
    return re.sub(r"[^a-z0-9]", "_", i)


def nginx_conf(state):
    """The site's include: every variable the template reads, for every routed app."""
    lines = ["# Generated by irate-box (hub_control.py) from /etc/hub/access.json. Edits are overwritten."]
    for i in ROUTED:
        mode = state.get(i, ROUTED[i][0])
        lines.append(f'set $irate_box_auth_{var(i)} {"off" if mode == "public" else chr(34) + REALM + chr(34)};')
        lines.append(f'set $irate_box_off_{var(i)} "{"1" if mode == "off" else ""}";')
    return "\n".join(lines) + "\n"


def caddy_snippets(state, login_hash, directive="basic_auth"):
    """{file name: snippet} for the Caddyfile's per-route imports. <id>.caddy: nothing, the login
    or a 404; <id>-off.caddy: the 404 only (routes that always ask for the login, or must stay
    open). `directive` is "basicauth" on Caddy 2.6, as install.sh rewrites it there."""
    out = {}
    for i in ROUTED:
        mode = state.get(i, ROUTED[i][0])
        head = f"# Generated by irate-box (hub_control.py) from /etc/hub/access.json: {i} is {mode}.\n"
        gate = ("respond 404\n" if mode == "off" else
                f"{directive} {{\n\tadmin {login_hash}\n}}\n" if mode == "private" and not ROUTED[i][1] else "")
        out[f"{i}.caddy"] = head + gate
        out[f"{i}-off.caddy"] = head + ("respond 404\n" if mode == "off" else "")
    return out
